management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health,info"
server:
  port :  9003
  servlet:
    contextPath: /backend
spring:
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://localhost:8180/realms/dacs'
